import React, { useState, useEffect } from "react";
import ReactQuill from "react-quill";
import "react-quill/dist/quill.snow.css";
import productService from "../../services/productService";
import categoryService from "../../services/categoryService";
import woodTypeService from "../../services/woodTypeServices";
import toast from "../../utils/toast";

const API_BASE = import.meta.env.VITE_API_URL || "http://localhost:3212";

const ProductModal = ({ product, onClose, onSuccess }) => {
    const isEdit = Boolean(product);
    const [loading, setLoading] = useState(false);
    const [categories, setCategories] = useState([]);
    const [woodTypes, setWoodTypes] = useState([]);
    const [imagePreview, setImagePreview] = useState(null);
    const [imageFile, setImageFile] = useState(null);

    const [form, setForm] = useState({
        name: "",
        description: "",
        price: "",
        stock: "",
        categoryId: "",
        woodTypeId: "",
        difficulty: "",
        dimensions: "",
    });

    useEffect(() => {
        const loadMetadata = async () => {
            try {
                const [catRes, woodRes] = await Promise.all([
                    categoryService.getCategories(),
                    woodTypeService.getAll()
                ]);
                setCategories(Array.isArray(catRes) ? catRes : []);
                setWoodTypes(Array.isArray(woodRes) ? woodRes : []);
            } catch (err) {
                console.error("Error loading metadata:", err);
                toast.error("Không thể tải danh mục hoặc loại gỗ");
            }
        };

        loadMetadata();

        if (product) {
            setForm({
                name: product.name || "",
                description: product.description || "",
                price: product.price?.toString() || "",
                stock: product.stock?.toString() || "",
                categoryId: product.categoryId || "",
                woodTypeId: product.woodTypeId || "",
                difficulty: product.difficulty || "",
                dimensions: product.dimensions || "",
            });
            if (product.image) {
                setImagePreview(
                    product.image.startsWith("http")
                        ? product.image
                        : `${API_BASE}${product.image}`
                );
            }
        }
    }, [product]);

    const handleChange = (e) => {
        const { name, value } = e.target;
        setForm((f) => ({ ...f, [name]: value }));
    };

    const handleDescriptionChange = (value) => {
        setForm((f) => ({ ...f, description: value }));
    };

    const handleImageChange = (e) => {
        const file = e.target.files?.[0];
        if (file) {
            setImageFile(file);
            setImagePreview(URL.createObjectURL(file));
        }
    };

    const handleSubmit = async (e) => {
        e.preventDefault();

        if (!form.name.trim()) {
            toast.warning("Vui lòng nhập tên sản phẩm");
            return;
        }
        if (!form.price || parseFloat(form.price) <= 0) {
            toast.warning("Vui lòng nhập giá hợp lệ");
            return;
        }
        if (!isEdit && !imageFile) {
            toast.warning("Vui lòng chọn hình ảnh sản phẩm");
            return;
        }

        setLoading(true);
        try {
            const formData = new FormData();
            formData.append("name", form.name.trim());
            // Slug is generated by backend
            formData.append("description", form.description);
            formData.append("price", form.price);
            formData.append("stock", form.stock || "0");
            if (form.categoryId) formData.append("categoryId", form.categoryId);
            if (form.woodTypeId) formData.append("woodTypeId", form.woodTypeId);
            if (form.difficulty) formData.append("difficulty", form.difficulty);
            if (form.dimensions) formData.append("dimensions", form.dimensions);
            if (imageFile) formData.append("image", imageFile);

            if (isEdit) {
                await productService.update(product.id, formData);
                toast.success("Cập nhật sản phẩm thành công!");
            } else {
                await productService.create(formData);
                toast.success("Thêm sản phẩm thành công!");
            }
            onSuccess();
        } catch (err) {
            console.error("Error saving product:", err);
            toast.error(err.response?.data?.message || "Không thể lưu sản phẩm");
        } finally {
            setLoading(false);
        }
    };

    const quillModules = {
        toolbar: [
            [{ header: [1, 2, 3, false] }],
            ["bold", "italic", "underline", "strike"],
            [{ list: "ordered" }, { list: "bullet" }],
            [{ color: [] }, { background: [] }],
            ["clean"],
        ],
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50 p-4 overflow-y-auto">
            <div className="bg-white rounded-2xl shadow-xl w-full max-w-4xl max-h-[90vh] overflow-y-auto">
                <div className="p-6 border-b border-gray-100 flex justify-between items-center sticky top-0 bg-white z-10">
                    <h2 className="text-xl font-bold text-gray-800">
                        {isEdit ? "Chỉnh sửa sản phẩm" : "Thêm sản phẩm mới"}
                    </h2>
                    <button onClick={onClose} className="text-gray-400 hover:text-gray-600 p-2">
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" /></svg>
                    </button>
                </div>

                <form onSubmit={handleSubmit} className="p-6 space-y-6">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        {/* Left Column */}
                        <div className="space-y-6">
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Tên sản phẩm <span className="text-red-500">*</span></label>
                                <input
                                    type="text"
                                    name="name"
                                    value={form.name}
                                    onChange={handleChange}
                                    className="w-full border rounded-lg px-4 py-2 focus:ring-2 focus:ring-violet-500 focus:outline-none"
                                    placeholder="Tên sản phẩm..."
                                />
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">Giá (VNĐ) <span className="text-red-500">*</span></label>
                                    <input
                                        type="number"
                                        name="price"
                                        value={form.price}
                                        onChange={handleChange}
                                        className="w-full border rounded-lg px-4 py-2 focus:ring-2 focus:ring-violet-500 focus:outline-none"
                                        placeholder="0"
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">Tồn kho</label>
                                    <input
                                        type="number"
                                        name="stock"
                                        value={form.stock}
                                        onChange={handleChange}
                                        className="w-full border rounded-lg px-4 py-2 focus:ring-2 focus:ring-violet-500 focus:outline-none"
                                        placeholder="0"
                                    />
                                </div>
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">Danh mục</label>
                                    <select
                                        name="categoryId"
                                        value={form.categoryId}
                                        onChange={handleChange}
                                        className="w-full border rounded-lg px-4 py-2 focus:ring-2 focus:ring-violet-500 focus:outline-none"
                                    >
                                        <option value="">-- Chọn --</option>
                                        {categories.map((c) => (
                                            <option key={c.id} value={c.id}>{c.name}</option>
                                        ))}
                                    </select>
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">Loại gỗ</label>
                                    <select
                                        name="woodTypeId"
                                        value={form.woodTypeId}
                                        onChange={handleChange}
                                        className="w-full border rounded-lg px-4 py-2 focus:ring-2 focus:ring-violet-500 focus:outline-none"
                                    >
                                        <option value="">-- Chọn --</option>
                                        {woodTypes.map((w) => (
                                            <option key={w.id} value={w.id}>{w.name}</option>
                                        ))}
                                    </select>
                                </div>
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">Độ khó</label>
                                    <select
                                        name="difficulty"
                                        value={form.difficulty}
                                        onChange={handleChange}
                                        className="w-full border rounded-lg px-4 py-2 focus:ring-2 focus:ring-violet-500 focus:outline-none"
                                    >
                                        <option value="">-- Chọn --</option>
                                        <option value="EASY">Dễ</option>
                                        <option value="MEDIUM">Trung bình</option>
                                        <option value="HARD">Khó</option>
                                    </select>
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">Kích thước</label>
                                    <input
                                        type="text"
                                        name="dimensions"
                                        value={form.dimensions}
                                        onChange={handleChange}
                                        className="w-full border rounded-lg px-4 py-2 focus:ring-2 focus:ring-violet-500 focus:outline-none"
                                        placeholder="VD: 20x30 cm"
                                    />
                                </div>
                            </div>
                        </div>

                        {/* Right Column */}
                        <div className="space-y-6">
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Hình ảnh {!isEdit && <span className="text-red-500">*</span>}</label>
                                <div className="border-2 border-dashed border-gray-300 rounded-lg p-4 text-center hover:border-violet-500 transition-colors">
                                    <input
                                        type="file"
                                        accept="image/*"
                                        onChange={handleImageChange}
                                        className="hidden"
                                        id="modal-product-image"
                                    />
                                    <label htmlFor="modal-product-image" className="cursor-pointer block">
                                        {imagePreview ? (
                                            <img
                                                src={imagePreview}
                                                alt="Preview"
                                                className="mx-auto h-48 object-contain rounded-md"
                                            />
                                        ) : (
                                            <div className="py-8 text-gray-400">
                                                <svg className="w-12 h-12 mx-auto mb-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>
                                                <span>Chọn hình ảnh</span>
                                            </div>
                                        )}
                                    </label>
                                </div>
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Mô tả chi tiết</label>
                                <div className="h-64">
                                    <ReactQuill
                                        theme="snow"
                                        value={form.description}
                                        onChange={handleDescriptionChange}
                                        modules={quillModules}
                                        className="h-48"
                                    />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className="flex justify-end gap-3 pt-6 border-t border-gray-100">
                        <button
                            type="button"
                            onClick={onClose}
                            className="px-6 py-2 rounded-lg bg-gray-100 text-gray-700 font-medium hover:bg-gray-200"
                        >
                            Hủy
                        </button>
                        <button
                            type="submit"
                            disabled={loading}
                            className="px-6 py-2 rounded-lg bg-violet-600 text-white font-semibold hover:bg-violet-700 disabled:opacity-50 flex items-center gap-2"
                        >
                            {loading && <div className="animate-spin rounded-full h-4 w-4 border-2 border-white border-t-transparent"></div>}
                            {isEdit ? "Cập nhật" : "Tạo sản phẩm"}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default ProductModal;
